### PR TITLE
Fix KVO-related race condition that could cause an overrelease of `GTMLogLevelFilter`.

### LINKED ISSUE #238: Crash when set a value in UserDefaults
We use two libraries which are using UserDefaults.standard (your's and Armchair).
Because of some intersection in how these libraries operate with UserDefaults, we get a crash in our application.
As a temporary solution we made a fork of smaller and simpler library - Armchair and use non-standard UserDefaults.
For example:

```let userDefaults = UserDefaults(suiteName: "com.github.CompanyName.VendorName")!```

Maybe you could do something similar or maybe you have your own decision about that.

Helpful links:

Our problem solution
https://github.com/roxiemobile-forks/Armchair/commit/cb64462a38a1eb6dbcb63fc4991ce2da1d342b1a

NSUserDefaults KVO conflict with Adobe DMP
https://github.com/Adobe-Marketing-Cloud/mobile-services/issues/284

### PR DESCRIPTION
**Pull request by fumoboy007**
Fixes #238.

### CODE REVIEW

File: Foundation/GTMLogger.m [hunk 1]
```diff
@@ -505,31 +522,12 @@ @implementation GTMLogLevelFilter
...
-                       options:NSKeyValueObservingOptionNew
-                       context:nil];
-
     verboseLoggingEnabled_ = IsVerboseLoggingEnabled(userDefaults_);
   }
 
   return self;
 }
 
-- (void)dealloc {
```
Comment (thomasvl) [inline Foundation/GTMLogger.m:526]: Does it make sense to keep this and assert that userDefaults_ is nil?

Comment (fumoboy007) [reply Foundation/GTMLogger.m:526]: Sounds like a good idea. What kind of assertion should we use? `NSAssert`, `NSException`, or something else? I’m thinking an `NSInternalInconsistencyException`.

Comment (thomasvl) [reply Foundation/GTMLogger.m:526]: `NSAssert` should be fine since it would likely be an issue in some impl calling these methods.  You should be able to wrap the whole dealloc in `defined(NS_BLOCK_ASSERTIONS)` so it won't even exist when the `NSAssert` is going to be compiled away.

Comment (fumoboy007) [reply Foundation/GTMLogger.m:526]: Added an assertion using `_GTMDevAssert`. Thanks!

I’ll leave out the `#if !defined(NS_BLOCK_ASSERTIONS)` part because it adds extra maintenance cost (needs to be kept in sync with the implementation of `dealloc` and the implementation of the `_GTMDevAssert` macro) and extra code (including a clarifying comment) without much benefit in this case.

**Review by thomasvl — APPROVED** [review]
